//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="SingleNews"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class SingleNews : IContentItemFieldsSource, INewsFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.SingleNews";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// SingleNewsProcessing.
		/// </summary>
		public IEnumerable<TagReference> ArticleType { get; set; }
		public IEnumerable<TagReference> TypeOfStock { get; set; }
		public IEnumerable<TagReference> StockAge { get; set; }
		public IEnumerable<TagReference> ProductionStage { get; set; }
		public IEnumerable<TagReference> InformationSource { get; set; }
		public IEnumerable<TagReference> ArticleLength { get; set; }




		/// <summary>
		/// NewsFieldsName.
		/// </summary>
		public string NewsFieldsName { get; set; }


		/// <summary>
		/// NewsFieldsDescription.
		/// </summary>
		public string NewsFieldsDescription { get; set; }


		/// <summary>
		/// NewsFieldsShortDescription.
		/// </summary>
		public string NewsFieldsShortDescription { get; set; }

		/// <summary>
		/// NewsFieldsImage.
		/// </summary>
		public IEnumerable<Image> NewsFieldsImage { get; set; }

		
	}
}