//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace KwFeeds
{
	/// <summary>
	/// Represents a content item of type <see cref="HomePageBanner"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class HomePageBanner : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KwFeeds.HomePageBanner";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// tag.
		/// </summary>
		public string tag { get; set; }


		/// <summary>
		/// title.
		/// </summary>
		public string title { get; set; }


		/// <summary>
		/// button_text.
		/// </summary>
		public string button_text { get; set; }
	}
}