//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DancingGoat.Models
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="INewsFields"/> reusable schema assigned.
	/// </summary>
	public interface INewsFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "NewsFields";


		/// <summary>
		/// NewsFieldsName.
		/// </summary>
		public string NewsFieldsName { get; set; }


		/// <summary>
		/// NewsFieldsDescription.
		/// </summary>
		public string NewsFieldsDescription { get; set; }


		/// <summary>
		/// NewsFieldsShortDescription.
		/// </summary>
		public string NewsFieldsShortDescription { get; set; }


		/// <summary>
		/// NewsFieldsImage.
		/// </summary>
		public IEnumerable<Image> NewsFieldsImage { get; set; }
	}
}