//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace KwFeeds
{
	/// <summary>
	/// Represents a page of type <see cref="ProductPage"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ProductPage : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KwFeeds.ProductPage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// PageHeaderContent.
		/// </summary>
		public string PageHeaderContent { get; set; }


		/// <summary>
		/// RelatedProducts.
		/// </summary>
		public IEnumerable<SingleProduct> RelatedProducts { get; set; }


		/// <summary>
		/// GUID.
		/// </summary>
		public Guid GUID { get; set; }
	}
}