//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace KwFeeds
{
	/// <summary>
	/// Represents a page of type <see cref="KwHomePage"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class KwHomePage : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KwFeeds.KwHomePage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// hero_section.
		/// </summary>
		public IEnumerable<HomePageBanner> hero_section { get; set; }


		/// <summary>
		/// products_of_the_month.
		/// </summary>
		public IEnumerable<SingleProduct> products_of_the_month { get; set; }


		/// <summary>
		/// products.
		/// </summary>
		public IEnumerable<SingleProduct> products { get; set; }


		/// <summary>
		/// about.
		/// </summary>
		public IEnumerable<About> about { get; set; }
	}
}