//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="Products"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Products : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.Products";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Name.
		/// </summary>
		public string Name { get; set; }
		public string Description { get; set; }


		/// <summary>
		/// isProductofTheMonth.
		/// </summary>
		public bool isProductofTheMonth { get; set; }


		/// <summary>
		/// NutritionalInformation.
		/// </summary>
		public string NutritionalInformation { get; set; }


		/// <summary>
		/// Ingredients.
		/// </summary>
		public string Ingredients { get; set; }


		/// <summary>
		/// FeedingGuidelines.
		/// </summary>
		public string FeedingGuidelines { get; set; }


		/// <summary>
		/// UsageTips.
		/// </summary>
		public string UsageTips { get; set; }


		/// <summary>
		/// StorageInstructions.
		/// </summary>
		public string StorageInstructions { get; set; }


		/// <summary>
		/// CafePhoto.
		/// </summary>
		public IEnumerable<Image> CafePhoto { get; set; }


		/// <summary>
		/// CafeHealthBenefits.
		/// </summary>
		public string CafeHealthBenefits { get; set; }


		/// <summary>
		/// CafeCuppingOffer.
		/// </summary>
		// public IEnumerable<Coffee> CafeCuppingOffer { get; set; }
	}
}