//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="SingleProduct"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class SingleProduct : IContentItemFieldsSource, IProductFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.SingleProduct";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// SingleProductProcessing.
		/// </summary>
		public IEnumerable<TagReference> SingleProductProcessing { get; set; }


		/// <summary>
		/// SingleProductTastes.
		/// </summary>
		public IEnumerable<TagReference> SingleProductTastes { get; set; }


		/// <summary>
		/// ProductFieldsName.
		/// </summary>
		public string ProductFieldsName { get; set; }


		/// <summary>
		/// ProductFieldsDescription.
		/// </summary>
		public string ProductFieldsDescription { get; set; }


		/// <summary>
		/// ProductFieldsShortDescription.
		/// </summary>
		public string ProductFieldsShortDescription { get; set; }
		public string ProductFieldNutritionalInformation { get; set; }
		public string ProductFieldIngredients { get; set; }
		public string ProductFieldFeedingGuidelines { get; set; }
		public string ProductFieldUsageTips { get; set; }
		public string ProductFieldHandlingInstructions { get; set; }
		public string ProductFieldHealthBenefits { get; set; }


		/// <summary>
		/// ProductFieldsImage.
		/// </summary>
		public IEnumerable<Image> ProductFieldsImage { get; set; }
	}
}