//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.MediaLibrary;

namespace KwFeeds
{
	/// <summary>
	/// Represents a content item of type <see cref="SingleProduct"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class SingleProduct : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KwFeeds.SingleProduct";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// name.
		/// </summary>
		public string name { get; set; }


		/// <summary>
		/// nutritional_information.
		/// </summary>
		public string nutritional_information { get; set; }


		/// <summary>
		/// ingredients.
		/// </summary>
		public string ingredients { get; set; }


		/// <summary>
		/// feeding_guidelines.
		/// </summary>
		public string feeding_guidelines { get; set; }


		/// <summary>
		/// usage_tips.
		/// </summary>
		public string usage_tips { get; set; }


		/// <summary>
		/// storage_instructions.
		/// </summary>
		public string storage_instructions { get; set; }


		/// <summary>
		/// health_benefits.
		/// </summary>
		public string health_benefits { get; set; }


		/// <summary>
		/// images.
		/// </summary>
		public IEnumerable<AssetRelatedItem> images { get; set; }
	}
}