//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace KwFeeds
{
	/// <summary>
	/// Represents a content item of type <see cref="SingleProduct"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class SingleProduct : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KwFeeds.SingleProduct";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// ProductLogo.
		/// </summary>
		public ContentItemAsset ProductLogo { get; set; }


		/// <summary>
		/// ProductImage.
		/// </summary>
		public ContentItemAsset ProductImage { get; set; }


		/// <summary>
		/// ProductDescription.
		/// </summary>
		public string ProductDescription { get; set; }


		/// <summary>
		/// ProductAdditionalInfo.
		/// </summary>
		public string ProductAdditionalInfo { get; set; }


		/// <summary>
		/// GUID.
		/// </summary>
		public Guid GUID { get; set; }
	}
}